# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-04 11:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import employees.validators


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_task_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Płaca podstawowa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(validators=[employees.validators.valid_date], verbose_name='Koniec zlecenia'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(validators=[employees.validators.valid_date], verbose_name='Początek zlecenia'),
        ),
    ]
