# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20170404_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='accomplishment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='target',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(verbose_name='Koniec zlecenia'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(verbose_name='Początek zlecenia'),
        ),
    ]
