# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20170405_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='accomplishment',
            field=models.IntegerField(default=0, verbose_name='Wykonanie'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(blank=True, to='employees.Employee', verbose_name='Pracownicy'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Zamknij zlecenie'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target',
            field=models.IntegerField(verbose_name='Cel'),
        ),
    ]
