# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-06 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20170406_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='stand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.Stand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Zajmij zlecenie'),
        ),
    ]
