# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_stand'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='stand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Stand', verbose_name='Stanowisko'),
        ),
    ]
