# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20170410_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_employed',
            field=models.BooleanField(default=True),
        ),
    ]
