# Generated by Django 2.0.5 on 2018-07-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_is_employed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_employed',
            field=models.BooleanField(default=True, verbose_name='Pracownik jest zatrudniony'),
        ),
        migrations.AlterField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_available': 'True'}, to='employees.Employee', verbose_name='Pracownicy'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stand',
            field=models.ForeignKey(on_delete=True, to='employees.Stand', verbose_name='Stanowisko'),
        ),
    ]
